### PR TITLE
Fix apt-key deprecation for Ubuntu 21.04 +

### PR DESCRIPTION
**Pull request by TN-1**
This change installs the public key to /etc/apt/trusted.gpg.d - While this is "acceptable" behaviour it is not best practice. However given apt-key is deprecated and is planned to be removed in 22.04 so this method is prefered and should be used for 21.04 +            
For more information and for instructions to utilize best practices, see https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key  
It only takes about 20 minutes to move things over to /usr/local/share/keyrings. Given it isn't nearly default behaviour though its not worth adding it to this script.

### CODE REVIEW

**Comment by cryinkfly** [comment]
I thank you for your help and for this information! 🙂

So would it make sense to include the whole thing for the other Ubuntu versions?

**Comment by TN-1** [comment]
Happy to help :)  
  
I wouldn't bother with the earlier versions IMO, it will just throw a deprecation message and then it can just be worried about when said user upgrades if they feel like it.  
  
I just decided to do some research into the deprecation last night, saw the askubuntu link above and decided to convert my system over and figured i'd fix the script while I was at it. But like I said, its not enforced until 22.04 so its just nicety at this point.

**Comment by cryinkfly** [comment]
Okay, I know about that and I will probably take a closer look at it in the near future. 🙂

I've included you on this list: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/blob/main/COMMUNITY.md

**Comment by johannesE** [comment]
I don't understand much about the issue here, but the script just didn't continue until I changed this change back to:
```
      14)
            debian-based-1 &&
            wget -q https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_21.04/Release.key -O Release.key -O- | sudo apt-key add - &&
            sudo apt-add-repository 'deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_21.04/ ./' &&
            debian-based-2 &&
            select-your-path
            ;;
      15)
```
This could be a temporary error due to a network failure, but somehow it was unable to verify the keys and therefore stopped. If anyone else runs into the issue, you can try this way.

The warning I got was: `signature not checked due to a missing key`. The tmp/360 folder was full of public keys, so that was not the issue. I don't really have more time for this, just wanted to mention it.

**Pull request merged**
